patrocars/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponse, HttpRequest

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('',include('montadoras.urls')),
]

patrocars/montadoras/urls.py
from django.urls import path, include
from .views import MontadoraView, ModeloVeiculoView, VeiculoView, admin

montadoras_routes = path('montadoras/',include(
    [
        path('criar/',MontadoraView.Create.as_view(),name='montadora_create'),
        path('editar/<int:pk>/',MontadoraView.Update.as_view(),name='montadora_put'),
        path('deletar/<int:pk>/',MontadoraView.Delete.as_view(),name='montadora_delete'),
    ]
))
    
modelos_routes = [
    path('',ModeloVeiculoView.ListAll,name='modelos_list'),
    path('criar/',ModeloVeiculoView.Create.as_view(),name='modelo_save'),
    path('editar/<int:pk>/',ModeloVeiculoView.Update.as_view(),name='modelo_put'),
    path('deletar/<int:pk>/',ModeloVeiculoView.Delete.as_view(),name='modelo_delete'),
]

veiculo_routes = [
    path('',VeiculoView.ListAll.as_view(),name='veiculos_list'),
    path('criar/',VeiculoView.Create.as_view(),name='veiculo_save'),
    path('editar/<int:pk>/',VeiculoView.Update.as_view(),name='veiculo_put'),
    path('deletar/<int:pk>/',VeiculoView.Delete.as_view(),name='veiculo_delete'),
]

urlpatterns = [
    path('',MontadoraView.ListAll.as_view(),name='montadoras_list'),
    path('admin/',admin,name='admin_page'),
    path('modelos/',include(modelos_routes)),
    path('veiculos/',include(veiculo_routes)),
    montadoras_routes
]  

patrocars/montadoras/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Montadora(models.Model):
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=200)
  avatar_url = models.CharField(max_length=200)
  country = models.CharField(max_length=100)
  foundation_year = models.IntegerField()

  class Meta:
        ordering = ['name','foundation_year']
  def __str__(self):
    return self.name

class ModeloVeiculo(models.Model):
  id = models.AutoField(primary_key=True)
  name = models.CharField(max_length=200)
  montadora_id = models.ForeignKey(Montadora,on_delete=models.CASCADE)
  valor_referencia = models.FloatField()
  motorizacao = models.FloatField()
  turbo = models.BooleanField()
  automatico = models.BooleanField()
  def __str__(self):
    return self.name

class Veiculo(models.Model):
  id = models.AutoField(primary_key=True)
  modelo_id = models.ForeignKey(ModeloVeiculo,on_delete=models.CASCADE)
  cor = models.CharField(max_length=150)
  ano_fabricacao = models.IntegerField()
  ano_modelo = models.IntegerField()
  valor = models.IntegerField()
  placa = models.CharField(max_length=20)
  vendido = models.BooleanField()
  def __str__(self):
    return self.cor
  
class MontadoraForm(ModelForm):
    class Meta:
        model = Montadora
        fields = ["name", "country", "foundation_year","avatar_url"]

class ModeloVeiculoForm(ModelForm):
    class Meta:
        model = ModeloVeiculo
        fields = ["name", "montadora_id", "valor_referencia","motorizacao","turbo","automatico"]

class VeiculoForm(ModelForm):
   class Meta:
        model = Veiculo
        fields = ["modelo_id", "cor", "ano_fabricacao","ano_modelo", "valor", "placa","vendido"]

patrocars/montadoras/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import requires_csrf_token
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from .models import Montadora, MontadoraForm, ModeloVeiculo, ModeloVeiculoForm, Veiculo, VeiculoForm
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

def admin(req):
    return render(req, "admin.html");

class MontadoraView:

    class Create(CreateView):
        model = Montadora
        form_class = MontadoraForm
        template_name = "montadoras/montadora_form.html"
        success_url = reverse_lazy("montadoras_list")
        context_object_name = 'montadora'

    class Update(UpdateView):
        model = Montadora
        form_class = MontadoraForm
        template_name = "montadoras/montadora_form.html"
        success_url = reverse_lazy("montadoras_list")
        context_object_name = 'montadora'

    class ListAll(ListView):
        model = Montadora
        template_name = "index.html"

    class Delete(DeleteView):
        model = Montadora
        success_url = reverse_lazy('montadoras_list')  # Redirecionar após a exclusão

        def post(self, request, *args, **kwargs):
            return self.delete(request, *args, **kwargs)
        
class ModeloVeiculoView:

    def ListAll(req: HttpRequest):
        object_list = ModeloVeiculo.objects.all().order_by("-id")
        template_name = "modelos/list_modelos.html"
        return render(req,template_name,context={"object_list":object_list})

    class Create(CreateView):
        model = ModeloVeiculo
        form_class = ModeloVeiculoForm
        template_name = "modelos/create_modelo.html"
        success_url = reverse_lazy("modelos_list")
        context_object_name = 'modelo'

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['montadoras'] = Montadora.objects.all()  # Passa o queryset para o template
            return context

    class Update(UpdateView):
        model = ModeloVeiculo
        form_class = ModeloVeiculoForm
        template_name = "modelos/create_modelo.html"
        success_url = reverse_lazy("modelos_list")
        context_object_name = 'modelo'

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['montadoras'] = Montadora.objects.all()  # Passa o queryset para o template
            return context
    
    class Delete(DeleteView):
        model = ModeloVeiculo
        success_url = reverse_lazy('modelos_list')  # Redirecionar após a exclusão

        def post(self, request, *args, **kwargs):
            return self.delete(request, *args, **kwargs)
        
class VeiculoView:

    class ListAll(ListView):
        model = Veiculo
        template_name = "veiculos/list_veiculos.html"

    class Create(CreateView):
        model = Veiculo
        form_class = VeiculoForm
        template_name = "veiculos/create_veiculo.html"
        success_url = reverse_lazy("veiculos_list")

    class Update(UpdateView):
        model = Veiculo
        form_class = VeiculoForm
        template_name = "veiculos/update_veiculo.html"
        success_url = reverse_lazy("veiculos_list")
    
    class Delete(DeleteView):
        model = Veiculo
        success_url = reverse_lazy('veiculos_list')  # Redirecionar após a exclusão

        def post(self, request, *args, **kwargs):
            return self.delete(request, *args, **kwargs)

patrocars/montadoras/templates/admin.html
{% extends "base.html" %}

{% block title %} Admin {% endblock %}

{% load static %}

{% block content %}

<div class="md:px-12 pt-16 md:pl-20 max-md:pl-4 h-full" id="background">
    <!-- <style>
        #background {

            background-color: #FFF;
            background-image: url("data:image/svg+xml,%3Csvg width='42' height='44' viewBox='0 0 42 44' xmlns='http://www.w3.org/2000/svg'%3E%3Cg id='Page-1' fill='none' fill-rule='evenodd'%3E%3Cg id='brick-wall' fill='%239C92AC' fill-opacity='0.4'%3E%3Cpath d='M0 0h42v44H0V0zm1 1h40v20H1V1zM0 23h20v20H0V23zm22 0h20v20H22V23z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
        }
    </style> -->
    <div class="flex items-center gap-3">
        <img src="{% static 'icons/lock.svg' %}" width="18" height="18"/>
        <h2 class="text-4xl font-extrabold mt-2">Acesso do funcionário</h2>
    </div>
    <hr class=" mb-4 h-0.5 border-t-0 bg-neutral-100 dark:bg-black/10"/>
    <ul class="space-y-1 w-full text-gray-700 text-xl list-disc list-inside">
        <li >
            <a class="hover:underline pointer" href="/montadoras/criar">Adicionar montadora</a>
        </li>
        <li >
            <a class="hover:underline pointer" href="/modelos/criar">Adicionar modelos</a>
        </li>
        <li>
            <a class="hover:underline pointer" href="/veiculos/criar">Adicionar veículos</a>
        </li>
        <li>
            <a class="hover:underline pointer" href="/veiculos">Listar veículos</a>
        </li>
    </ul>

</div>

{% endblock %}

patrocars/montadoras/templates/index.html
{% extends "base.html" %}

{% block title %} Montadoras {% endblock %}

{% load static %}

{% block content %}
    <div class="px-12 pt-16">

        {% if object_list %}
            <div class="flex flex-col justify-between">
                <div class="flex gap-8">
                    <div>
                        <h1 class="mb-4 mt-8 font-extrabold tracking-widest text-blue-600 text-6xl">PATRO<span
                                class="text-gray-900">CARS</span></h1>

                        <h3 class="mb-4 mt-4 text-5xl leading-none tracking-tight text-gray-900 ">
                            Tire o sonho do carro próprio do papel <span
                                class="underline underline-offset-3 decoration-2 decoration-blue-400 dark:decoration-blue-600">hoje.</span>
                        </h3>
                        <p class="text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">Empresa líder em
                            satisfação com compra de automóveis na América Latina*. Desde 1995 colocando mais alguns
                            pares de rodas estrada afora.</p>
                    </div>
                    <img height="100" width="300" src="{% static 'images/initial.png' %}"/>
                </div>

                <hr class="my-12 h-0.5 border-t-0 bg-neutral-100 dark:bg-black/10"/>

                <h4 class="text-4xl text-center font-bold">Nossas parceiras</h4>
                <div class="flex items-center justify-center gap-3">
                    {% for montadora in object_list %}
                        <a href="{% url 'montadora_put' montadora.id%}" class="w-56 py-8 bg-white pointer">
                            <div class="flex justify-center items-center">
                                {% if montadora.avatar_url %}
                                    <img class="grayscale" width="50" height="80"
                                         src="{% static montadora.avatar_url %}"
                                         alt="Avatar da Montadora">
                                {% endif %}
                            </div>
                            <h5 class="mb-2 text-2xl tracking-tight text-center text-gray-900">
                                {{ montadora.name }}
                            </h5>

                            <!-- <a class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" href="/montadoras/editar/{{montadora.id}}">Editar</a> | <form class="inline" action="{% url 'montadora_delete' montadora.id %}"" method="post">{% csrf_token %}
      <input class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" type="submit" value="Deletar"> -->
                            <!-- </form> -->
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% else %}
            <div>Sem montadoras no momento...</div>
        {% endif %}
    </div>

{% endblock %}

patrocars/montadoras/templates/modelos/create_modelo.html
{% extends "base.html" %} 
{% block title %} Adicionar modelo {% endblock %} 
{% block content %}

{% load static %}
<div class="relative h-full flex flex-col justify-center items-center overflow-hidden bg-no-repeat bg-center bg-cover">   
  <h5 class="mb-2  z-10 text-black text-4xl text-center font-bold tracking-tight text-gray-900" >
  {% if modelo %} EDITAR{% else %} CADASTRAR {% endif %} MODELO</h5>

  <form class="relative z-10 block flex flex-col gap-4 w-96 p-6 bg-blue-300 bg-opacity-90 border border-white border-2 rounded-lg shadow dark:border-white border-dashed" method="post">
      {% csrf_token %}
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg text-xs focus:ring-blue-500 focus:border-blue-500" type="text" name="name" placeholder="Nome..." value="{{ modelo.name }}">
<style>
  select {
    display: block;
    width: 100%;
    padding: 0.5rem; /* 2 = 0.5rem */
    font-size: 0.875rem; /* text-sm */
    color: #1f2937; /* text-gray-900 */
    border: 1px solid #d1d5db; /* border-gray-300 */
    border-radius: 0.375rem; /* rounded-lg */
    background-color: #f3f4f6; /* bg-gray-100 */
    transition: border-color 0.2s, box-shadow 0.2s; /* para animações suaves */
}

select:focus {
    border-color: #3b82f6; /* focus:border-blue-500 */
    box-shadow: 0 0 0 4px rgba(59, 130, 246, 0.5); /* para simular o ring azul */
}
</style>
  {{form.montadora_id}}

<!-- <div class="flex justify-between items-center">
  <select id="small" name="montadora_id" class="block w-full p-2 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-100 focus:ring-blue-500 focus:border-blue-500">
    {% for obj in montadoras %}
    <option value="{{ obj.id }}" {% if modelo.montadora_id == obj.id %}selected{% endif %}>
      {{ obj }}
    </option>
  {% endfor %}
  </select>
</div> -->
   
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg text-xs focus:ring-blue-500 focus:border-blue-500" type="number" name="valor_referencia" placeholder="Valor de referência" value="{{ modelo.valor_referencia }}"/>
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500" type="number" name="motorizacao" placeholder="Motorização" value="{{ modelo.motorizacao }}"/>

      <div class="flex items-center ps-2 border border-gray-200 rounded bg-gray-200">
        <!-- <input type="checkbox" name="turbo" id="id_turbo" placeholder="Turbo" value="{{ modelo.turbo }}" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"/> -->
        {{form.turbo}}
        <label for="id_turbo" class="w-full mt-0.5 py-4 ms-2 text-sm font-medium text-gray-900 ">Turbo</label>
      </div>
      <div class="flex items-center ps-2 border border-gray-200 rounded bg-gray-200">
        <!-- <input type="checkbox" name="automatico" id="id_automatico" placeholder="Automático" value="{{ modelo.automatico }}" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"/> -->
        {{form.automatico}}
        <label for="id_automatico" class="w-full mt-0.5 py-4 ms-2 text-sm font-medium text-gray-900 ">Automático</label>
      </div>

      <input 
      {% if modelo %}
      value="ATUALIZAR" 
      {% else %}
      value="SALVAR"
      {% endif %}
      
      type="submit" class="text-yellow-300 font-bold bg-[#1da1f2] hover:bg-[#1da1f2]/90 focus:ring-4 focus:outline-none focus:ring-[#1da1f2]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#1da1f2]/55 me-2 mb-2 w-full" id="submitBtn"/>
  </form>
</div>


{% endblock %}

patrocars/montadoras/templates/modelos/list_modelos.html
{% extends "base.html" %}

{% block title %} Modelos {% endblock %}

{% block title_page %} Lista de Modelos {% endblock %}

{% block content %}
{% if object_list %}
<ul>
  {% for modelo in object_list %}
  <li>{{ modelo.name }}<a class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" href="/modelos/editar/{{modelo.id}}">Editar</a> | <form class="inline" action="{% url 'modelo_delete' modelo.id %}"" method="post">{% csrf_token %}
    <input class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" type="submit" value="Deletar">
  </form></li>
  {% endfor %}
</ul>
{% else %}
<div>Sem modelos no momento...</div>
{% endif %}
<a class="text-blue-600 hover:underline" href="/modelos/criar"> Adicionar modelo </a>

{% endblock %}

patrocars/montadoras/templates/modelos/update_modelo.html
{% extends "base.html" %} {% block title %} Editar modelo {% endblock %} 
{% block title_page %} {% endblock %} {% block content %}
<div class="h-full flex justify-center items-center">
  <form
    class="block flex flex-col gap-4 max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700"
    action="{% url 'modelo_put' object.id %}"
    method="post"
  >
    {% csrf_token %}
    <h5
      class="mb-2 text-2xl text-center font-bold tracking-tight text-gray-900 dark:text-white"
    >
      Atualizar modelo
    </h5>
    {{ form.as_p }}
    <!-- <input class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" type="text" name="name" placeholder="Nome da Montadora.." />
    <input  class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" type="text" name="country" placeholder="Pais..." />
    <input
    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      type="text"
      name="foundation_year"
      placeholder="Ano da Montadora"
    /> -->
    <input
      type="submit"
      value="Salvar Modelo"
      class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
    />
  </form>
</div>
{% endblock %}

patrocars/montadoras/templates/montadoras/montadora_form.html
{% extends "base.html" %}

{% block title %}{% if montadora %} Editar {% else %} Cadastrar {% endif %} montadora {% endblock %}

{% block content %}

{% load static %}
<div class="relative h-full flex flex-col justify-center items-center overflow-hidden bg-no-repeat bg-center bg-cover"   

{% if montadora %} 
    style="background-image: url('{% static montadora.avatar_url %}')"  
{% endif %}>
{% if montadora %} 
    <div class="absolute inset-0 bg-black bg-opacity-50 backdrop-blur-sm"></div>
{% endif %}
  

  <h5 class="mb-2  z-10 text-white text-4xl text-center font-bold tracking-tight text-gray-900" 
  {% if not montadora %} 
  style="color: black;"
{% endif %}>
  {% if montadora %} EDITAR{% else %} CADASTRAR {% endif %} MONTADORA</h5>

  <form class="relative z-10 block flex flex-col gap-4 w-96 p-6 bg-blue-300 bg-opacity-90 border border-white border-2 rounded-lg shadow dark:border-white border-dashed" method="post">
      {% csrf_token %}
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg text-xs focus:ring-blue-500 focus:border-blue-500" type="text" name="name" placeholder="Nome..." value="{{ montadora.name }}">
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg text-xs focus:ring-blue-500 focus:border-blue-500" type="text" name="country" placeholder="País" value="{{ montadora.country }}">
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500" type="number" name="foundation_year" placeholder="Ano de fundação" value="{{ montadora.foundation_year }}">
      <input class="block text w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500" type="text" name="avatar_url" placeholder="HREF para a logo" value="{{ montadora.avatar_url }}">

      <input 
      {% if montadora %}
      value="ATUALIZAR" 
      {% else %}
      value="SALVAR"
      {% endif %}
      
      type="submit" class="text-yellow-300 font-bold bg-[#1da1f2] hover:bg-[#1da1f2]/90 focus:ring-4 focus:outline-none focus:ring-[#1da1f2]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#1da1f2]/55 me-2 mb-2 w-full" id="submitBtn"/>
  </form>
</div>


{% endblock %}

patrocars/montadoras/templates/veiculos/create_veiculo.html
{% extends "base.html" %}

{% block title %} Adicionar veiculo {% endblock %}

{% block title_page %}  {% endblock %}

{% block content %}
<div class="h-full flex justify-center items-center">
  <form class="block flex flex-col gap-4 max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700" action="{% url 'veiculo_save' %}" method="post">
    {% csrf_token %}
    <h5 class="mb-2 text-2xl text-center font-bold tracking-tight text-gray-900 dark:text-white">Novo veiculo</h5>
    {{ form.as_p }}
    <input type="submit" value="Salvar Veiculo" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"/>
  </form>
</div>
{% endblock %}

patrocars/montadoras/templates/veiculos/list_veiculos.html
{% extends "base.html" %}

{% block title %} Veículos {% endblock %}

{% block title_page %} Lista de Veículos {% endblock %}

{% block content %}
{% if object_list %}
<ul>
  {% for veiculo in object_list %}
  <li>{{ veiculo.cor }} | <a class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" href="/veiculos/editar/{{veiculo.id}}">Editar</a> | <form class="inline" action="{% url 'veiculo_delete' veiculo.id %}"" method="post">{% csrf_token %}
    <input class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" type="submit" value="Deletar">
  </form></li>
  {% endfor %}
</ul>
{% else %}
<div>Sem veículos no momento...</div>
{% endif %}
<a class="text-blue-600 hover:underline" href="/veiculos/criar"> Adicionar veículo </a>

{% endblock %}

patrocars/montadoras/templates/veiculos/update_veiculo.html
{% extends "base.html" %}

{% block title %} Editar veículo {% endblock %}

{% block title_page %}  {% endblock %}

{% block content %}
<div class="h-full flex justify-center items-center">
  <form class="block flex flex-col gap-4 max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700" action="{% url 'veiculo_put' object.id %}" method="post">
    {% csrf_token %}
    <h5 class="mb-2 text-2xl text-center font-bold tracking-tight text-gray-900 dark:text-white">Atualizar veículo</h5>
    {{ form.as_p }}
    <input type="submit" value="Salvar Veículo" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"/>
  </form>
</div>
{% endblock %}

patrocars/templates/montadora_update_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Adicionar montadora</title>
  </head>
  <body>
    <header>
      <h1>Adicionar montadora</h1>
    </header>
  </body>
  <main>
    <h2>Atualizar Montadora</h2>
    <form action="{% url 'montadora_update' %}" method="post">
      {% csrf_token %}
      <input type="text" name="name" placeholder="Nome da Montadora.." />
      <input type="text" name="country" placeholder="Pais..." />
      <input
        type="text"
        name="foundation_year"
        placeholder="Ano da Montadora"
      />
      <input type="submit" value="Salvar Montadora" />
    </form>
  </main>
</html>

patrocars/templates/montadoras_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Atualizar montadora</title>
  </head>
  <body>
    <header>
      <h1>Atualizar montadora</h1>
    </header>
  </body>
  <main>
    <h2>Nova Montadora</h2>
    <form action="{% url 'montadora_save' %}" method="post">
      {% csrf_token %}
      <input
        type="text"
        name="name"
        placeholder="Nome da Montadora.."
        value="{{montadora.name}}"
      />
      <input
        type="text"
        name="country"
        placeholder="Pais..."
        value="{{montadora.country}}"
      />
      <input
        type="text"
        name="foundation_year"
        placeholder="Ano da Montadora"
        value="{{montadora.foundation_year}}"
      />
      <input type="submit" value="Salvar" />
    </form>
  </main>
</html>